name: task1.1

on:
  push:
    branches:
      - main

jobs:
  ci-integrated :
    name: pragya ka sikhaya hua pehla task
    runs-on: ubuntu-latest
    steps:
      - name: cistarted
        run: echo "cistarted"

      - name: OS info
        run:  uname -a
    
    

   
