name: context

on:
  push:
    branchs:
      main

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
    
        run: echo " build ${{ github.run_number }} on $date " | GITHUB_OUTPUT

        run: echo $GITHUB_OUTPUT

#Use `github.run_number` to create a build version string like `"Build #42 on 2024-01-15"`. Use `date` command for the date. 
#Write this to `$GITHUB_OUTPUT` and reference it in the next step.
