name: cron job

on:
  schedule:
    - cron: '04 12 * * 1-7'
      timezone: "Asia/Kolkata"


jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: print greet
        run: echo "Good morning, team!"
