name: cron job

on:
  push:
    branches:
      main

env:

  COMPANY: Acme
  VERSION: 1.0


jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: print greet
        run: echo "Good morning, team!"

      - name: company name
        run: echo "${{ env.COMPANY }}"

      - name: version name 
        run: echo "${{ env.VERSION }}"

