
# Create a matrix job that tests on `ubuntu-20.04`, `ubuntu-22.04`, and `ubuntu-latest`. Install `tree` using `apt-get` 
# and run `tree /usr/bin | head -20`. Note version differences.

name: matrix-Strategy

on:
  push:
    branches:
      main


jobs:
  test:
    strategy:
      matrix: 
        os: [ ubuntu-latest, macOS ]
        node-version: [18,20]
    runs-on: ${{matrix.os}}

    steps:
      - name: Testing Node
        run: echo " Testing Node ${{ matrix.node-version }} on ${{ matrix.os }} "

      

       #Create a matrix strategy that combines `os` and `node-version` (e.g., Node 18 and 20 on both Ubuntu and macOS). 
        #That gives 4 combinations. Print `"Testing Node ${{ matrix.node-version }} on ${{ matrix.os }}"`