name: input parameter

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      app_name:
        description: "give it a suitable app name "
        type: string 
        required: true
        
      replicas:
        description: "update replicas no "
        type:  numbers
        default: 2
        
      debug_mode:
        description: "update debug_mode"
        type: boolean
         
        
        
jobs:
  input-parameter:
    name: input parameters
    runs-on: ubuntu-latest

    steps:
      - name: print app_name
        run: echo "app name is ${{ inputs.app_name }}"

      - name: replicas
        run: echo " ${{ inputs.replicas }}"

      - name: debug_mode
        run: echo " ${{ inputs.debug_mode }}"


    
        
  
      