name: input parameter

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      environments:
        description: "select the Environment"
        type: choice 
        required: true
        option: 
          -staging
          -production
        
  

jobs:
  input_parameter:
    name: task1.2
    runs-on: ubuntu-latest

    steps:
      - name: print input parameter
        run: echo "Deploying to ${{ inputs.environments }}"


    
        
  
      