name: System Info

on:
  workflow_call:
  workflow_dispatch:
     

jobs:
  System-Info:
    name: task1.2
    runs-on: ubuntu-latest

    environment: staging

    steps:
      - name: print input parameter
        run: "Deploying to: ${{ inputs.environment }}"


    
        
  
      